# Плейбук. Применяем роли к хостам из группы db
# infra/production.yml
---
# - hosts: db
#   remote_user: root
#   roles:
#     - { role: 'createuser' }

- hosts: db
  roles:
    # - { role: 'common' }
    # - { role: 'docker' }
    # - { role: 'docker-compose-from-source' }
    # - { role: 'nginx' }
    - { role: 'runner' }


# production.yml
#    |
#    v
# "hosts: db" → ищет группу db в inventory → находит lf-app1
#    |
#    v
# на lf-app1 запускается роль swaptrasher
#    |
#    v
# если есть group_vars/db.yml → берутся переменные оттуда
