# Плейбук. Применяем роли к хостам из группы db
---
- hosts: db
  roles:
    # - { role: 'createuser' }
    # - { role: 'common' }
    ## - { role: 'docker' }
    # - { role: 'docker-compose-from-source' }
    ## - { role: 'swaptrasher' }
    - { role: 'nginx' }


# production.yml
#    |
#    v
# "hosts: db" → ищет группу db в inventory → находит lf-app1
#    |
#    v
# на lf-app1 запускается роль swaptrasher
#    |
#    v
# если есть group_vars/db.yml → берутся переменные оттуда
